id: AA46BE442
title: 'Gyang Lu: A Song of Calling from Afar'
type: translation
pechas:
- IDA7B2490
- I9CD3DCF3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:59:02.838246
  last_modified_at: 2023-01-04 12:59:02.838262
  collections:
  - Longchen Rabjam Series
  - Works of Tibetan Masters
alignment_to_base:
  IDA7B2490/1F77: 4ED4
  I9CD3DCF3/F4F6: 4ED4
